In [1]:
import numpy as np

In [2]:
x = np.dot([2j, 3j], [2j, 3j])
x

(-13+0j)

In [3]:
x = np.arange(0, 10).reshape(5, 2)
x

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [4]:
x.size

10

In [5]:
x.ndim

2

In [6]:
# memory (total number of bytes) occupied by an array
x.nbytes

40

In [7]:
# data type of elements
x.dtype

dtype('int32')

# Transposing an array

In [8]:
np.transpose(x)

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [11]:
x.T # Alternative of transpose

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

# Masked arrays